### PR TITLE
Pin `numpy~=1.0`

### LINKED ISSUE #46: Unit Test Workflow Fails; NumPy v2.0
Workflow fails due do to [NumPy v2.0](https://numpy.org/devdocs/release/2.0.0-notes.html) just released June 2024.  Recommend pinning to previous version for the time being?

See details: https://github.com/NOAA-OWP/lstm/actions/runs/9667310741/job/26668843222#step:7:39

For experiment, I removed all package versioning (`xarray` and `llvm-openmp`) and pinned python to v3.10.  Workflow still fails.

### PR DESCRIPTION
**Pull request by aaraney**
See #46 for more detail.

fixes #46

### CODE REVIEW

**Comment by aaraney** [comment]
Assume that the `macos` failures are b.c. an `arm` runner picked the job up. Curious if `conda` is necessary to install this now. Moving this to draft to test that theory out.

**Comment by aaraney** [comment]
Good thing, is it looks like pinning `numpy` has fixed the issue.

**Comment by aaraney** [comment]
Looks like that fixed it.

**Review by madMatchstick — APPROVED** [review]
Thanks for the quick fix!

**Pull request merged**
